config/routes.rb
QwinixUtilizationSheet::Application.routes.draw do
  

  devise_for :admins

  devise_for :users

  resources :users
  resources :employees do
    resources :projects
  end

  root :to => 'employees#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :designation, :name
  has_many :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name,:first_week, :second_week, :third_week, :fourth_week, :fifth_week, :sixth_week
  belongs_to :employee
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:image,:remote_image_url
  attr_accessible :designation, :name
  has_many :projects

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_url, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employees, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
  def footer
    
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @employee=Employee.find(params[:employee_id])
    @projects = @employee.projects

    respond_to do |format|
      format.html 
      format.json { render json: @projects }
    end
  end

  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def new
    @employee=Employee.find(params[:employee_id])
    @projects=@employee.projects.build(params[:project])

    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @employee=Employee.find(params[:employee_id])
    @projects = @employee.projects.build(params[:project])

    respond_to do |format|
      if @projects.save
        format.html { redirect_to employee_projects_url, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to employee_projects_url, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  protected
  
  def after_sign_in_path_for(resource)
    root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_footer.html.erb
<div class="wall container container-fluid" >

  <% if @employees.nil? %>
  <% else %>
    <div class="pagination pagination-small">
      <ul>
        <% @employees.each do |employee| %>
          <li class="active">
            <%= link_to employee.name.capitalize, :controller => "projects", :action => "index", :employee_id => employee.id, :employee_name => employee.name,:style => "font-weight:bold;color:black;" %>
          </li>
        <% end %></ul>
    </div>
  <% end %>
</div>
<div class=" navbar-inner">

</div>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :designation %><br />
    <%= f.text_field :designation %>
  </div>
  <div class="actions">
    <%= f.submit 'Save',:class => "btn"  %>
    <%= link_to 'Back', employees_path,:class => "btn" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="container container-fluid wall">
  <h1>Editing employee</h1>
  <%= render 'form' %>
</div>

app/views/employees/index.html.erb
<div class="wall container container-fluid">

  <div class="row-fluid">
    <div class="span12" style="text-align: center;">
      <h1>Qwinix Utilization Dashboard</h1>
    </div>
  </div>
  <h3 class="pull-left">Employees</h3>

  <div class="pull-right">
    <%= link_to 'New Employee', new_employee_path,:class => 'btn'  %>&nbsp;&nbsp;&nbsp;&nbsp;
  </div>
  <div class="row-fluid">
    <div class="span12" style="height:350px; overflow: auto;">
      <table class="table table-condensed table-striped">
        <tr>
          <th>Name</th>
          <th>Designation</th>
          <%  d=Date.today%>
          <%  w=d.beginning_of_week(start_day = :monday)%>
          <th><%= w.strftime("%d-%b-%y") %></th>
          <th><%= (w += 7).strftime("%d-%b-%y") %></th>
          <th><%= (w += 7).strftime("%d-%b-%y") %></th>
          <th><%= (w += 7).strftime("%d-%b-%y") %></th>
          <th><%= (w += 7).strftime("%d-%b-%y") %></th>
          <th><%= (w+= 7).strftime("%d-%b-%y") %></th>
          <th></th><th></th>
        </tr>

        <% @employees.each do |employee| %>
          <tr>
            <td><%= employee.name.capitalize %></td>
            <td><%= employee.designation.capitalize %></td>
            <td><%=  employee.projects.sum(:first_week)*2.5%> %</td>
            <td><%=  employee.projects.sum(:second_week)*2.5%> %</td>
            <td><%=  employee.projects.sum(:third_week)*2.5%> %</td>
            <td><%=  employee.projects.sum(:fourth_week)*2.5%> %</td>
            <td><%=  employee.projects.sum(:fifth_week)*2.5%> %</td>
            <td><%=  employee.projects.sum(:sixth_week)*2.5%> %</td>
            <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
            <td><%= link_to 'Destroy', employee, method: :delete, :remote => true,data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </table>
    </div>

  </div>

</div>

app/views/employees/new.html.erb
<div class="container container-fluid wall">
  <h1>New employee</h1>
  <%= render 'form' %>
</div>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Designation:</b>
  <%= @employee.designation %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QwinixUtilizationSheet</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="wall container container-fluid ">
          <img src="/assets/logo.png" alt="logo" class="img"/>
          <div class="" style="float: right;padding-top:10px;">
            <% if user_signed_in? %>
              Signed in as <%= current_user.email %>
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete,:class => "btn" %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path,:class => "btn"  %>  <%= link_to "sign in", new_user_session_path ,:class => "btn" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= yield %>
    <%=  render 'footer'%>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for([@employee,@projects]) do |f| %>
  <% if @projects.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projects.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @projects.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="container container-fluid wall">
  <div class="pull-right" >
    <%= link_to 'Add Project', new_employee_project_path,:class => 'btn', :style=>"margin-top:10px;" %>&nbsp;&nbsp;&nbsp;&nbsp;
  </div>
  <h3>Projects for <%=  @employee.name.capitalize %></h3>

  <table class="table table-striped table-condenced">
    <tr>
      <th>Name</th>
      <%  d=Date.today%>
      <%  w=d.beginning_of_week(start_day = :monday)%>
      <th><%= w.strftime("%d-%b-%y") %></th>
      <th><%= (w += 7).strftime("%d-%b-%y") %></th>
      <th><%= (w += 7).strftime("%d-%b-%y") %></th>
      <th><%= (w += 7).strftime("%d-%b-%y") %></th>
      <th><%= (w += 7).strftime("%d-%b-%y") %></th>
      <th><%= (w += 7).strftime("%d-%b-%y") %></th>
      <th></th>
    </tr>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <%= form_for([@employee,project]) do |f| %>
          <td><%=  f.text_field :first_week,:style => "width:50px;height:13px;" %></td>
          <td><%=  f.text_field :second_week,:style => "width:50px;height:13px;"%></td>
          <td><%=  f.text_field :third_week,:style => "width:50px;height:13px;"%></td>
          <td><%=  f.text_field :fourth_week,:style => "width:50px;height:13px;"%></td>
          <td><%=  f.text_field :fifth_week,:style => "width:50px;height:13px;"%></td>
          <td> <%=  f.text_field :sixth_week,:style => "width:50px;height:13px;"%></td>
          <td><%= f.submit 'save' %></td>
        <% end %>
       
      </tr>
    <% end %>
  </table>

  <br />

  <%= link_to 'Back', employees_path,:class => "btn" %>
</div>

app/views/projects/new.html.erb
<div class="wall container-fluid">
<h1>New project</h1>

<%= render 'form' %>
<%= link_to 'Back', employee_projects_path,:class => "btn" %>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :designation %><br />
    <%= f.text_field :designation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="wall container-fluid">
 
<div class="row-fluid">
  <div class="span12" style="text-align: center;">
    <h1>Qwinix Utilization Dashboard</h1>
  </div>
</div>
<h3 class="pull-left">Employees</h3>

<table class="table table-condensed table-striped">
  <tr>
    <th>Name</th>
    <th>Designation</th>
    <th><%=  Date.today%></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.designation %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete,:remote=>true, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="wall container-fluid">
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
 <p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Designation:</b>
  <%= @user.designation %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>